# Quiz Classification 

Kuis ini merupakan bagian dari proses penilaian *Algoritma Corporate Training*. Selamat atas selesainya materi pertama dalam Klasifikasi dalam Machine Learning. Kami akan melakukan penilaian berupa kuis untuk menguji praktek teknik pembuatan model klasifikasi yang sudah Anda pelajari. Pengerjaan kuis diharapkan dapat dilakukan di dalam kelas, silakan hubungi tim instruktur kami jika Anda melewatkan kesempatan untuk mengambilnya di kelas.

Pada quiz berikut, Anda akan diminta membuat model classification sebagai penilaian pemahaman mengenai materi klasifikasi yang sudah dipelajari sebelumnya.

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# suppress scientific notation
np.set_printoptions(suppress=True) # numpy output
pd.set_option('display.float_format', lambda x: '%.3f' % x) # pandas output

# suppress warning
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

## Eksplorasi Data

Pada quiz ini, kita akan melakukan pemodelan data Geotech, dari dataset [Cone Penetration Test](http://140.112.12.21/issmge/tc304.htm?=6) untuk kasus Klasifikasi Tanah berdasarkan [paper berikut](https://www.mdpi.com/2076-3417/13/9/5758).

Klasifikasi tanah memiliki peran penting dalam bidang *geotechnical engineering*, terutama dalam asesmen respons lokasi terhadap event seismik. Pengkategorian tanah yang tepat akan membantu dalam memahami sifat dinamis tanah dan bagaimana gempa bumi mempengaruhi perilaku tanah. Klasifikasi tanah tradisional biasanya dilakukan berdasarkan data CPT.

Selama bertahun-tahun, [cone penetration test (CPT)](https://www.youtube.com/watch?v=98Q9Huc9Us0) telah menjadi metode utama untuk melakukan eksplorasi lapangan dalam *geotechnical engineering*. Uji ini dilakukan dengan memasukkan instrumen berbentuk kerucut ke dalam tanah dengan kecepatan penetrasi yang konsisten dan mengukur resistensi ujung kerucut (qc) dan gesekan selongsong (fs). CPT secara konsisten memberikan hasil yang baik mengenai kedalaman tanah. Selain itu, CPT merupakan metode yang cepat dan hemat biaya untuk mengumpulkan data lapangan guna memperkirakan parameter untuk berbagai aplikasi.

Hasil CPT ini selanjutnya yang berguna dalam klasifikasi tanah, sebagai **data scientist** Anda diminta untuk mengembangkan model untuk mengklasifikasikan tanah berdasarkan pengukuran CPT ini.

Sebelum membuat model, silahkan memahami data terlebih dahulu. Load data yang diberikan (`data_input/soil_behaviour_type.csv`) dan simpan ke dalam objek bernama `soil`, kemudian cek tipe data yang ada.

In [32]:
soil = pd.read_csv('data_input/soil_behaviour_type.csv')

Berdasarkan investigasi di atas, data soil memiliki 221139 baris dan 4 kolom. Berikut adalah deskripsi detail dari setiap kolom:

- `depth`: kedalaman di bawah permukaan tanah ke ujung penetrometer kerucut, z (mm).
- `qc`: nilai resistansi ujung kerucut, qc (MPa).
- `fs`:  nilai gesekan selongsong, fs (kPa).
- `soil_type`: Jenis tanah, 6 jenis.

Sebelum melakukan modeling, luangkan waktu Anda untuk melakukan langkah eksplorasi. Silahkan liat nilai unik dari `soil_type`

*Hint: Silahkan gunakan method `.unique()`*

In [33]:
# code here
soil['soil_type'].unique()

array(['gravelly sands to dense sand', 'sands', 'sand mixtures', 'clays',
       'silt mixtures', 'organic soil'], dtype=object)

Silahkan untuk melakukan eksplorasi untuk melihat rata-rata kedalaman CPT masing-masing tanah.

*Hint: Anda dapat menggunakan cross tab untuk melihat rata-rata kedalaman masing-masing jenis tanah*

In [34]:
soil.head()

   depth       qc     fs                     soil_type
0  0.015 3930.000  5.400  gravelly sands to dense sand
1  0.020 5060.000  5.400  gravelly sands to dense sand
2  0.025 5350.000  9.800                         sands
3  0.030 5620.000  9.800                         sands
4  0.035 5950.000 11.700                         sands

In [35]:
# code here
soil.groupby('soil_type').mean('qc').reset_index().sort_values(by='depth', ascending=False)

                      soil_type  depth       qc      fs
1  gravelly sands to dense sand  2.899 2885.822 143.514
4                         sands  2.335 2951.190 172.096
3                 sand mixtures  0.303  447.948  43.451
5                 silt mixtures  0.175  187.079  31.024
2                  organic soil  0.168   25.490  41.086
0                         clays  0.129   79.494  34.044

___
1. Berdasarkan eksplorasi di atas, jenis tanah (`soil_type`) apa yang memiliki rata-rata kedalaman CPT yang paling dangkal?

- [ ] silt mixtures
- [ ] sand mixtures	
- [ ] clays
- [ ] sands
___

## Cross-Validation

Sebelum kita membuat model, kita harus membagi dataset menjadi data train dan test. Silahkan bagi data dengan proporsi 80% train dan 20% test.

Dalam melakukan splitting data silahkan gunakan `random_state = 0`.

In [36]:
# splitting data
from sklearn.model_selection import train_test_split
# your code here
# define predictor & target variable
y = soil['soil_type']
x = soil.drop(columns='soil_type')

# cross validation
x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                      random_state=0, 
                                                      test_size=0.2)

# Model Fitting

## Decision Tree

Mari buat model Decision Tree dan simpan ke dalam objek `model_dt`. Untuk melakukan *tuning* model, mari kita atur parameter :

- `max_depth = 7`
- `min_samples_leaf = 20`
- `min_sample_split = 10`
- `random_state=123`

In [37]:
# your code here
from pyexpat import model
from sklearn.tree import DecisionTreeClassifier

# create model here
model_dt = DecisionTreeClassifier(random_state=123,max_depth=7,min_samples_leaf=20,min_samples_split=10)
model_dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=7, min_samples_leaf=20, min_samples_split=10,
                       random_state=123)

In [ ]:
# visualization
from sklearn.tree import plot_tree
plt.figure(figsize=(15,15), dpi=150)
plot_tree(model_dt, 
          feature_names=x_train.columns, 
          filled=True, 
          rounded=True);

---
2. Pada model Decision Tree, parameter min_samples_split=10 mengacu pada...
    - [ ] Jumlah minimum observasi pada internal node adalah 10. Jika tidak terpenuhi, maka tidak dilakukan percabangan.
    - [ ] Jumlah minimum observasi pada simpul daun adalah 10
    - [ ] Jumlah simpul internal yang terbentuk pada pohon adalah 10
    - [ ] Jumlah simpul daun yang terbentuk pada pohon adalah 10 
---

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree, export_text
plt.figure(figsize=(20,10), dpi=300)
plot_tree(model,
          feature_names=x_train.columns,
          max_depth=2,
          class_names=['clays', 'gravelly sands to dense sand', 'organic soil',
       'sand mixtures', 'sands', 'silt mixtures'],
          filled=True,
          rounded=True);

InvalidParameterError: The 'decision_tree' parameter of plot_tree must be an instance of 'sklearn.tree._classes.DecisionTreeClassifier' or an instance of 'sklearn.tree._classes.DecisionTreeRegressor'. Got <module 'pyexpat.model'> instead.

___
3. Berdasarkan plot tersebut, manakah dari interpretasi berikut yang BENAR?
    - [ ] data yang memiliki 4335 >= `qc` >= 2265 diharapkan masuk ke jenis tanah gravelly sands to dense sand
    - [ ] data yang memiliki `qc` <= 2265 dan `fs` <= 285.05 diharapkan masuk ke jenis tanah clays
    - [ ] data yang memiliki `qc` >= 4335 dan `fs` >= 285.05 diharapkan masuk ke jenis tanah sands
___

## Random Forest

Model terakhir yang ingin kita buat adalah Randon Forest. Di bawah ini merupakan keunggulan dari model Random Forest:

- Automatic feature selection
- Mereduksi bias pada model karena melakukan aggregasi dari hasil beberapa decision tree
- Menghasilkan estimasi out-of-box error yang tidak bias

Sekarang, coba buat model random forest dan simpan model dalam objek `model_rf`. Model tersebut dibuat menggunakan *hyperparameter* di bawah ini:

- `n_estimator = 250` 
- `random_state = 123` 
- `ood_score = True`

In [ ]:
# fill in the blank

from sklearn.ensemble import RandomForestClassifier

# create and fitting your model here
model_rf = RandomForestClassifier(n_estimators=250,random_state=123,oob_score=True)

Dalam praktiknya, random forest telah memiliki estimasi out-of-bag (OOB) yang merepresentasikan akurasi pada *out-of-bag data* (data yang tidak diambil ketika sampling/tidak digunakan dalam pembuatan random forest).

---
___
4. Berdasarkan nilai oob score pada `model_rf`, bagaimana cara menginterpretasikan out-of-bag score dari model?
  - [ ] Kita memiliki akurasi 99.8% pada *unseen data*
  - [ ] Kita memiliki error 0.02% pada data train
  - [ ] Kita memiliki akurasi 99.8% pada data soil
  - [ ] Kita memiliki error 0.02% pada data train
  
---

In [ ]:
# code here
model_rf.fit(x_train, y_train)
model_rf.oob_score_

0.9984625037448208

# Prediksi Model 

## Decision Tree
Setelah membangun model, kini kita dapat memprediksi data test menggunakan `model_dt`.

In [ ]:
# your code here
y_pred_dt = model_dt.predict(x_test)

## Random Forest
  
Setelah membangun model, kini kita dapat memprediksi data test menggunakan `model_rf`.

In [ ]:
# your code here
y_pred_rf = model_rf.predict(x_test)

# Evaluasi Model 

Buatlah confusion matrix pada model decisio  tree maupun random forest lalu carilah nilai accuracy, recall, dan precision untuk masing-masing model.

In [ ]:
# fill in the blank code
from sklearn.metrics import accuracy_score, recall_score, precision_score, classification_report

# model Decision Tree
print(classification_report(
    y_true=y_test,
    y_pred=y_pred_dt,
    target_names=['clays', 'gravelly sands to dense sand', 'organic soil',
       'sand mixtures', 'sands', 'silt mixtures'],
    digits=5))

                              precision    recall  f1-score   support

                       clays    0.83333   0.66667   0.74074        15
gravelly sands to dense sand    0.97330   0.98604   0.97963     19264
                organic soil    0.70588   1.00000   0.82759        12
               sand mixtures    0.93548   0.96667   0.95082        90
                       sands    0.98897   0.97878   0.98385     24831
               silt mixtures    0.93333   0.87500   0.90323        16

                    accuracy                        0.98178     44228
                   macro avg    0.89505   0.91219   0.89764     44228
                weighted avg    0.98189   0.98178   0.98179     44228

In [ ]:
# Model Random Forest
print(classification_report(
    y_true=y_test,
    y_pred=y_pred_rf,
    target_names=['clays', 'gravelly sands to dense sand', 'organic soil',
       'sand mixtures', 'sands', 'silt mixtures'],
    digits=5))

                              precision    recall  f1-score   support

                       clays    0.87500   0.93333   0.90323        15
gravelly sands to dense sand    0.99855   0.99870   0.99862     19264
                organic soil    1.00000   0.91667   0.95652        12
               sand mixtures    1.00000   0.98889   0.99441        90
                       sands    0.99895   0.99887   0.99891     24831
               silt mixtures    0.93750   0.93750   0.93750        16

                    accuracy                        0.99871     44228
                   macro avg    0.96833   0.96233   0.96487     44228
                weighted avg    0.99871   0.99871   0.99871     44228

# Komparasi Model

---
1. Sebagai seorang *data scientist*, kita diminta untuk menghasilkan *rule-based model* yang dapat dengan mudah diimplementasikan pada sistem yang sudah ada. Model apa yang paling baik untuk digunakan?
  - [ ] Decision Tree karena model mudah ditranslasikan menjadi suatu set aturan prediksi
  - [ ] Random Forest karena dapat dilakukan perunutan balik aturan prediksi berdasarkan informasi *variable importance*. 
  
---

6. Dari seluruh model yang telah dibuat, model mana yang memiliki performa paling baik dalam mengidentifikasi tanah apabila dilihat dari nilai recall? -> Melihat weighted average dari nilai recall

  - [ ] Decision Tree
  - [ ] Random Forest